# SPDX-FileCopyrightText: 2026 diffo-dev
# SPDX-License-Identifier: Apache-2.0

defmodule Ieee1164.Resolver do
  @moduledoc """
  Resolves `std_ulogic` into `std_logic` by *deriving* the resolution rules
  from the ieee1164 knowledge graph — never by transcribing the standard's
  table. The hard-coded `resolution_table` is only ever an oracle to check
  against (see the tests).

  The strength lattice is read straight from the artefact's edges:

    * `FORCES` / `WEAKLY_FORCES` order the knowns (0,1 over W over L,H)
    * `POISONS` / `PROPAGATES` lift `X` / `U` above the real drivers
    * `YIELDS_TO` settles the rest — `Z` yields to all, `X` (and `-`) yield to
      `U`. The explicit `X YIELDS_TO U` is what places `U` above `X` without
      importing any "propagates beats poisons" precedence.

  From that order: the stronger driver wins; equal-strength drivers that
  disagree birth the tier's unknown (0/1 → X, L/H → W); `-` is indifferent
  (`RESOLVES_AS X`); and a lone driver passes through unresolved.
  """

  @order ~w(U X 0 1 Z W L H -)

  @doc "The nine values in IEEE 1164 order — `U X 0 1 Z W L H -`, indices 0..8."
  def order, do: @order

  @doc """
  Resolve a 1-d vector of drivers into a single resolved value.

  Accepts the drivers as **value strings** (`["0", "1", "Z"]` → `"X"`), as
  **`u8` indices** into `order/0` (`[2, 3, 4]` → `1`), or as a 1-d **`Nx`
  tensor** of those indices (→ a scalar `:u8` tensor). A single driver resolves
  to itself — the standard's single-driver carve-out, so a lone `-` stays `-`;
  two or more fold pairwise, and order does not matter (resolution is
  commutative).
  """
  def resolve([head | _] = values) when is_binary(head), do: resolve(values, rules())

  def resolve([head | _] = indices) when is_integer(head) do
    indices |> Enum.map(&Enum.at(@order, &1)) |> resolve() |> index()
  end

  def resolve(%Nx.Tensor{} = drivers) do
    drivers |> Nx.to_flat_list() |> resolve() |> Nx.tensor(type: :u8)
  end

  def resolve([v], _rules), do: v
  def resolve([first | rest], rules), do: Enum.reduce(rest, first, &resolve2(&2, &1, rules))

  @doc """
  The full 9×9 resolution matrix as an `Nx.Tensor` of `:u8`, generated by
  exercising the resolver over every ordered pair. Each cell is the index into
  `order/0` of the resolved value.
  """
  def matrix do
    rules = rules()
    rows = for a <- @order, do: for(b <- @order, do: index(resolve([a, b], rules)))
    Nx.tensor(rows, type: :u8)
  end

  # ─── Pairwise resolution ──────────────────────────────────────────────────

  defp resolve2(a, b, %{resolves_as: ra, tier: tier, conflict: conflict}) do
    a = Map.get(ra, a, a)
    b = Map.get(ra, b, b)
    ta = Map.fetch!(tier, a)
    tb = Map.fetch!(tier, b)

    cond do
      a == b -> a
      ta > tb -> a
      tb > ta -> b
      true -> Map.fetch!(conflict, ta)
    end
  end

  defp index(v), do: Enum.find_index(@order, &(&1 == v))

  # ─── Rules derived from the artefact ──────────────────────────────────────

  @doc false
  def rules do
    graph = Ieee1164.ieee1164().graph
    name = Map.new(graph.nodes, fn n -> {n.id, n.properties["name"]} end)
    edges = Enum.map(graph.relationships, fn r -> {name[r.from_id], r.type, name[r.to_id]} end)

    resolves_as = for {a, "RESOLVES_AS", b} <- edges, into: %{}, do: {a, b}
    tier_values = Enum.reject(@order, &Map.has_key?(resolves_as, &1))

    dom = dominance(edges, tier_values)
    tier = tiers(tier_values, dom)

    unobservable =
      for {a, "UNOBSERVABLE", _} <- edges, a in tier_values, into: MapSet.new(), do: a

    %{resolves_as: resolves_as, tier: tier, conflict: conflicts(tier_values, tier, unobservable)}
  end

  # `{stronger, weaker}` pairs. FORCES/WEAKLY_FORCES are pairwise; POISONS and
  # PROPAGATES dominate every real value; YIELDS_TO is the authority that breaks
  # the U/X tie (both claim "value", so it takes `X YIELDS_TO U` to order them).
  defp dominance(edges, vs) do
    vset = MapSet.new(vs)
    member? = &MapSet.member?(vset, &1)

    base =
      Enum.reduce(edges, MapSet.new(), fn {a, type, b}, acc ->
        cond do
          type in ["FORCES", "WEAKLY_FORCES"] and member?.(a) and member?.(b) ->
            MapSet.put(acc, {a, b})

          type in ["POISONS", "PROPAGATES"] and member?.(a) and b == "value" ->
            Enum.reduce(vs, acc, fn v, acc ->
              if v == a, do: acc, else: MapSet.put(acc, {a, v})
            end)

          true ->
            acc
        end
      end)

    Enum.reduce(edges, base, fn {a, type, b}, acc ->
      cond do
        type == "YIELDS_TO" and member?.(a) and member?.(b) ->
          acc |> MapSet.delete({a, b}) |> MapSet.put({b, a})

        type == "YIELDS_TO" and member?.(a) and b == "value" ->
          Enum.reduce(vs, acc, fn v, acc ->
            if v == a, do: acc, else: acc |> MapSet.delete({a, v}) |> MapSet.put({v, a})
          end)

        true ->
          acc
      end
    end)
  end

  # tier = length of the longest dominance chain beneath a value (Z = 0).
  defp tiers(vs, dom) do
    Enum.reduce(vs, %{}, fn v, cache -> elem(tier_of(v, dom, cache), 1) end)
  end

  defp tier_of(v, dom, cache) do
    case Map.fetch(cache, v) do
      {:ok, t} ->
        {t, cache}

      :error ->
        below = for {a, b} <- dom, a == v, do: b

        {max_below, cache} =
          Enum.reduce(below, {-1, cache}, fn u, {mx, c} ->
            {tu, c} = tier_of(u, dom, c)
            {max(mx, tu), c}
          end)

        t = max_below + 1
        {t, Map.put(cache, v, t)}
    end
  end

  # For an equal-strength conflict at tier `t`, the result is the lowest
  # unobservable value strictly above `t` — X for the forcing tier, W for the weak.
  defp conflicts(vs, tier, unobservable) do
    for t <- vs |> Enum.map(&Map.fetch!(tier, &1)) |> Enum.uniq(),
        up = vs |> Enum.filter(&(MapSet.member?(unobservable, &1) and Map.fetch!(tier, &1) > t)),
        up != [],
        into: %{} do
      {t, Enum.min_by(up, &Map.fetch!(tier, &1))}
    end
  end
end
